sudo: required
addons:
  chrome: stable

language: node_js
node_js:
- "10"

branches:
  only:
  - dev

before_script:
- npm install -g @angular/cli

script:
- ng build --dev --aot
- ng test

notifications:
  slack: ausgehfuchs:FUvpOCTSaulBcOJHW7vKl5AT
